### ISSUE TITLE
不知道能否提供完整的训练数据？

### ISSUE THREAD

**Issue by XYZliang** [Tang895/yolov5-apex-tang#1]
如题，我是一名本科生，已经保研，导师方向就是目标检测，所以想提前熟悉一下相关的内容，正好拿自己玩的apex下手。
数据集太痛苦了呜呜，不知能不能提供下您的训练集数据，我再自己搞一些，然后用yolov7去训练试试看

**Comment by Tang895** [comment]
很抱歉我模型是在一些QQ群和网上收集的，并没有数据集。
________________________________
发件人: ZhangLiang ***@***.***>
发送时间: 2022年12月14日 13:51
收件人: Tang895/yolov5-apex-tang ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Tang895/yolov5-apex-tang] 不知道能否提供完整的训练数据？ (Issue #1)


如题，我是一名本科生，已经保研，导师方向就是目标检测，所以想提前熟悉一下相关的内容，正好拿自己玩的apex下手。
数据集太痛苦了呜呜，不知能不能提供下您的训练集数据，我再自己搞一些，然后用yolov7去训练试试看

―

**Comment by XYZliang** [comment]
明白了，感谢回复！
